### ISSUE TITLE
Can pytest fixtures be distributed?

### ISSUE THREAD

**Issue by peterschutt** [topsport-com-au/starlite-saqlalchemy#106]
Fixtures such as the integration test client, and the caplog fixture would be of benefit downstream if there was a way to make them available.

**Comment by gazorby** [comment]
Maybe by writing a [pytest plugin](https://docs.pytest.org/en/7.1.x/how-to/writing_plugins.html#writing-your-own-plugin)?

I think it should be a matter of adding a `starlite_saqlalchemy.testing.pytest` module and updating `pyproject.toml`:

```toml
[tool.poetry.plugins."pytest11"]
"starlite_salqalchemy" = "starlite_saqlalchemy.testing.pytest"
```
