### ISSUE TITLE
feature: make run-app command an entrypoint

### ISSUE THREAD

**Issue by peterschutt** [topsport-com-au/starlite-saqlalchemy#243]

**Comment by gazorby** [comment]
Seems great! So something `poetry run run-app` would works out of the box?

**Comment by peterschutt** [comment]
That's the plan at least. I gave it a quick go before and it didn't work like I thought (hoped) it would with an editable install locally.

In downstream apps I've been putting this in pyproject:

```toml
[tool.poetry.scripts]
run-app = "starlite_saqlalchemy.scripts:run_app"
```

It also could be a CLI feature, `ssqa run` or something like that, and we tie it in with #221

**Comment by peterschutt** [comment]
Turns out this was simple, I was just missing the correct group name before.

```toml
[tool.poetry.plugins."console_scripts"]
run-app = "starlite_saqlalchemy.scripts:run_app"
```

With that, I can call `run-app` in downstream app and it runs that function as a script :+1:
